name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: production
    runs-on: ubuntu-22.04
    concurrency: main

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        run: |
          npm install --global corepack@0.34.0
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: pnpm
      
      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Configure environmemt
        run: echo 'APP_URL=${{ vars.APP_URL }}' >> packages/functions/.env

      - name: Select project
        run: pnpm firebase use ${{ vars.FIREBASE_PROJECT }}

      - name: Deploy
        run: pnpm firebase deploy
