name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: production
    runs-on: ubuntu-22.04
    concurrency: main

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        run: |
          npm install --global corepack@0.34.0
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Configure npm authentication
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm set "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Configure environmemt
        run: |
          echo 'APP_URL="${{ vars.APP_URL }}"' >> packages/functions/.env
          echo 'SES_REGION="${{ vars.SES_REGION }}"' >> packages/functions/.env
          echo 'SES_FROM_EMAIL="${{ vars.SES_FROM_EMAIL }}"' >> packages/functions/.env
          echo 'SES_FROM_NAME="${{ vars.SES_FROM_NAME }}"' >> packages/functions/.env
          echo 'SES_ACCESS_KEY_ID="${{ vars.SES_ACCESS_KEY_ID }}"' >> packages/functions/.env
          echo 'SES_SECRET_ACCESS_KEY="${{ secrets.SES_SECRET_ACCESS_KEY }}"' >> packages/functions/.env

      - name: Select project
        run: pnpm firebase use ${{ vars.FIREBASE_PROJECT }}

      - name: Deploy
        run: pnpm firebase deploy
